### ISSUE TITLE
Discord link absent from virgo.org?

### ISSUE THREAD

**Issue by jaekwon** [virgo-project/meta#1]
I couldn't find a discord link.  What's our policy on that? @nylira

**Comment by alessio** [comment]
This is a never-expiring link: https://discord.gg/ff2kSg8

**Comment by jaekwon** [comment]
I see, it's not possible because the links keep expiring?

**Comment by alessio** [comment]
I set no expiry time for the URL I posted above

**Comment by nylira** [comment]
The permanent  link to Discord is on the https://virgo.org/act page, which is linked from the site homepage. 
https://discord.gg/Y7E5hwj

**Comment by nylira** [comment]
I'm removing this repo because we aren't using it. If we later we have meta discussions we can re-create this repo.
